### ISSUE TITLE
Generation sometimes fails

### ISSUE THREAD

**Issue by AGronowski** [awslabs/stable-diffusion-aws-extension#230]
### Describe the bug

Clicking the generate on cloud button doesn't result in anything generated. Issue happens intermittently. 

### Expected Behavior

Images are generated.

### Current Behavior

```
Traceback (most recent call last):
  File "/home/sagemaker-user/.conda/envs/ai2/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/sagemaker-user/.conda/envs/ai2/lib/python3.10/site-packages/gradio/blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/sagemaker-user/.conda/envs/ai2/lib/python3.10/site-packages/gradio/blocks.py", line 1297, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/home/sagemaker-user/.conda/envs/ai2/lib/python3.10/site-packages/gradio/blocks.py", line 1272, in validate_outputs
    raise ValueError(
ValueError: An event handler didn't receive enough output values (needed: 3, received: 1).
Wanted outputs:
    [gallery, textbox, html]
Received outputs:
    [None]
```

I've been trying to debug this and I think the issue happens inside the `sagemaker_ui.process_result_by_inference_id(inference_id) function`. When I print `resp['status']` the output is `created` That function only checks for `resp['status'] == "failed"` and `resp['status'] == "succeed"` For some reason for me the status sometimes is `created,` causing the error. 

### Reproduction Steps

Click the generate button. Issue happens intermittently. Sometimes trying to generate images over and over again from multiple tabs simultanously makes it happen.

### Solution Version

v1.2.0-d328a45

### AWS Region. e.g., us-east-1

us-east-1

**Comment by alvindaiyan** [comment]
Thanks for your reporting, I will take a look

**Comment by AGronowski** [comment]
Not sure if autoscaling is working properly either, with multiple generations at a time nothing scaled up.

**Comment by alvindaiyan** [comment]
what you mean not working? Is the UI frozen? Can you try some screenshot and capture the webui logs for me to debug?

**Comment by AGronowski** [comment]
I'll do some more testing over the next few days and get back to you. Not sure yet if the issue is somewhere on my end. Not working meant things were running infinitely with no images showing and no error messages. Only happened when trying multiple generations at the same time, it worked ok with one generation at a time.

**Comment by AGronowski** [comment]
> what you mean not working? Is the UI frozen? Can you try some screenshot and capture the webui logs for me to debug?

@alvindaiyan 

I did some more testing and now the issue consistently happens with an unmodified newest version of the webui 1.6.0 and newest version of the aws extension so I don't think the issue is on my end. 

```Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 54.9s (import torch: 17.4s, import gradio: 4.1s, setup paths: 4.1s, initialize shared: 0.6s, other imports: 3.2s, setup codeformer: 0.6s, setup gfpgan: 0.2s, load scripts: 6.7s, create ui: 14.6s, gradio launch: 3.1s).
DEBUG:aws_extension.sagemaker_ui_tab:user admin logged in
DEBUG:aws_extension.sagemaker_ui_tab:user roles are: ['IT Operator']
DEBUG:main.py:v1-5-pruned-emaonly.safetensors
DEBUG:main.py:refiner 1 4
DEBUG:main.py:seed 4 10
DEBUG:main.py:extra options 10 10
DEBUG:aws_extension.cloud_infer_service.simple_sagemaker_infer:{'user_id': 'admin', 'task_type': 'txt2img', 'models': {'Stable-diffusion': ['realvisxlV20_v20Bakedvae.safetensors'], 'embeddings': []}, 'filters': {'createAt': 1697982066.695212, 'creator': 'sd-webui'}}
DEBUG:aws_extension.sagemaker_ui:resp["status"] is created
Traceback (most recent call last):
  File "/home/sagemaker-user/.conda/envs/ai2/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/sagemaker-user/.conda/envs/ai2/lib/python3.10/site-packages/gradio/blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/sagemaker-user/.conda/envs/ai2/lib/python3.10/site-packages/gradio/blocks.py", line 1297, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/home/sagemaker-user/.conda/envs/ai2/lib/python3.10/site-packages/gradio/blocks.py", line 1272, in validate_outputs
    raise ValueError(
ValueError: An event handler didn't receive enough output values (needed: 3, received: 1).
Wanted outputs:
    [gallery, textbox, html]
Received outputs:
    [None]
```
The only modification I did to the code is add the line
`logger.debug(f'resp["status"] is {resp["status"]}')` to 

```def process_result_by_inference_id(inference_id):
    image_list = []  # Return an empty list if selected_value is None
    info_text = ''
    infotexts = f"Inference id is {inference_id}, please check all historical inference result in 'Inference Job' dropdown list"
    json_list = []
    prompt_txt = ''

    resp = get_inference_job(inference_id)
    if resp is None:
        return image_list, info_text, plaintext_to_html(infotexts)
    else:
        if resp['taskType'] in ['txt2img', 'img2img', 'interrogate_clip', 'interrogate_deepbooru']:

            logger.debug(f'resp["status"] is {resp["status"]}')
            
            while resp['status'] == "inprogress":
                time.sleep(3)
                resp = get_inference_job(inference_id)
            if resp['status'] == "failed":
                infotexts = f"Inference job {inference_id} is failed, error message: {resp['sagemakerRaw']}"
                return image_list, info_text, plaintext_to_html(infotexts)
            elif resp['status'] == "succeed":
                if resp['taskType'] in ['interrogate_clip', 'interrogate_deepbooru']:
                    prompt_txt = resp['caption']
                    # return with default value, including image_list, info_text, infotexts
```

This outputs `DEBUG:aws_extension.sagemaker_ui:resp["status"] is created` The if statement never checks for ` resp['status'] == "created"`  so this results in the above error. I'm not sure why status is `created` rather than `inprogress`

**Comment by AGronowski** [comment]
This is the ouput in the webui: 
<img width="724" alt="Screenshot 2023-10-22 at 3 19 49 PM" src="https://github.com/awslabs/stable-diffusion-aws-extension/assets/15481637/1051c7fe-aed0-4d26-9e76-9b0a154fd403">

No images appear. And checking the logs of the instance, no log event appears.
<img width="1080" alt="Screenshot 2023-10-22 at 3 22 32 PM" src="https://github.com/awslabs/stable-diffusion-aws-extension/assets/15481637/ade14dd5-bf1f-496a-bcb4-47f6e3a3e102">

From time to time the images are generated successfully and appear in the webui. For the events listed in the logs, the images appeared successfully. But when the described issue happens nothing shows up at all in the logs, so it seems sometimes the request never gets sent to the endpoint.

**Comment by alvindaiyan** [comment]
Hi, can you check if your sagemaker endpoint has enabled auto scaling?

**Comment by alvindaiyan** [comment]
Hi, we've released new version, could you please try again to see if you can reproduce the bug?

**Comment by AGronowski** [comment]
It seems to be working now. Just doing the update alone didn't fix it, but I uninstalled everything, deleted everything from my aws account, and reinstalled the middleware from scratch as a new installation. Now looks like it's working
